name: ci 
on: 
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: |
          bazel build //...
          bazel build --config=asan //...
          bazel build --config=ubsan //...