name: ci 
on: 
  push:
    branches:
     - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: bazel build //...
      
      - name: Build with asan
        run: bazel build --config=asan //...
      
      - name: Build with ubsan
        run: bazel build --config=ubsan //...